name: example
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  re_highlight: ^0.0.3
  google_fonts: ^8.0.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  code_forge: { path: ../ }
  jinja_app_widgets_catalog:
    path: /Users/avo/Documents/Workplace/digital_pomegranate/jinja-app/projects/jinja_app_widgets_catalog
  intl: ^0.20.2
  flutter_quill:
    git:
      url: https://github.com/AvoMandjian/flutter-quill.git
      ref: DP
  flutter_quill_extensions:
    git:
      url: https://github.com/AvoMandjian/flutter-quill.git
      path: flutter_quill_extensions
      ref: DP

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
