import 'package:code_forge/code_forge/suggestion_model.dart';

/// Returns Swift-specific suggestions.
List<SuggestionModel> getSwiftSuggestions() {
  return [
    SuggestionModel(
      label: 'Function',
      description: 'Insert a Swift function',
      replacedOnClick: 'func functionName() {\n  \n}',
      openingTag: 'func',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Function with Return',
      description: 'Insert a Swift function with return type',
      replacedOnClick: 'func functionName() -> ReturnType {\n  \n}',
      openingTag: 'func',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Function with Parameters',
      description: 'Insert a Swift function with parameters',
      replacedOnClick:
          'func functionName(param1: Type1, param2: Type2) {\n  \n}',
      openingTag: 'func',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Class',
      description: 'Insert a Swift class',
      replacedOnClick: 'class ClassName {\n  \n}',
      openingTag: 'class',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Struct',
      description: 'Insert a Swift struct',
      replacedOnClick: 'struct StructName {\n  \n}',
      openingTag: 'struct',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Enum',
      description: 'Insert a Swift enum',
      replacedOnClick: 'enum EnumName {\n  case value1\n  case value2\n}',
      openingTag: 'enum',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Protocol',
      description: 'Insert a Swift protocol',
      replacedOnClick: 'protocol ProtocolName {\n  func method()\n}',
      openingTag: 'protocol',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Extension',
      description: 'Insert a Swift extension',
      replacedOnClick: 'extension TypeName {\n  \n}',
      openingTag: 'extension',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'If Statement',
      description: 'Insert a Swift if statement',
      replacedOnClick: 'if condition {\n  \n}',
      openingTag: 'if',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'If-Else',
      description: 'Insert a Swift if-else statement',
      replacedOnClick: 'if condition {\n  \n} else {\n  \n}',
      openingTag: 'if',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'If Let',
      description: 'Insert a Swift if let statement',
      replacedOnClick: 'if let value = optional {\n  \n}',
      openingTag: 'if',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Guard Statement',
      description: 'Insert a Swift guard statement',
      replacedOnClick: 'guard condition else {\n  return\n}',
      openingTag: 'guard',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Switch Statement',
      description: 'Insert a Swift switch statement',
      replacedOnClick: 'switch value {\ncase pattern:\n  \ndefault:\n  \n}',
      openingTag: 'switch',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'For Loop',
      description: 'Insert a Swift for loop',
      replacedOnClick: 'for item in collection {\n  \n}',
      openingTag: 'for',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'While Loop',
      description: 'Insert a Swift while loop',
      replacedOnClick: 'while condition {\n  \n}',
      openingTag: 'while',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Repeat-While',
      description: 'Insert a Swift repeat-while loop',
      replacedOnClick: 'repeat {\n  \n} while condition',
      openingTag: 'repeat',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Array',
      description: 'Insert a Swift array',
      replacedOnClick: 'var array: [Type] = []',
      openingTag: 'var',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Dictionary',
      description: 'Insert a Swift dictionary',
      replacedOnClick: 'var dict: [KeyType: ValueType] = [:]',
      openingTag: 'var',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Optional',
      description: 'Insert a Swift optional',
      replacedOnClick: 'var optional: Type? = nil',
      openingTag: 'var',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Optional Binding',
      description: 'Insert Swift optional binding',
      replacedOnClick: 'if let value = optional {\n  \n}',
      openingTag: 'if',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Closure',
      description: 'Insert a Swift closure',
      replacedOnClick: '{ (param) -> ReturnType in\n  return value\n}',
      openingTag: '{',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Defer',
      description: 'Insert a Swift defer statement',
      replacedOnClick: 'defer {\n  \n}',
      openingTag: 'defer',
      closingTag: '}',
    ),
  ];
}
