import 'package:code_forge/code_forge/suggestion_model.dart';

/// Returns PHP-specific suggestions.
List<SuggestionModel> getPhpSuggestions() {
  return [
    SuggestionModel(
      label: 'Function',
      description: 'Insert a PHP function',
      replacedOnClick: 'function functionName() {\n  \n}',
      openingTag: 'function',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Function with Parameters',
      description: 'Insert a PHP function with parameters',
      replacedOnClick: 'function functionName(\$param1, \$param2) {\n  \n}',
      openingTag: 'function',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Class',
      description: 'Insert a PHP class',
      replacedOnClick: 'class ClassName {\n  \n}',
      openingTag: 'class',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Class with Constructor',
      description: 'Insert a PHP class with constructor',
      replacedOnClick:
          'class ClassName {\n  public function __construct() {\n    \n  }\n}',
      openingTag: 'class',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Method',
      description: 'Insert a PHP method',
      replacedOnClick: 'public function methodName() {\n  \n}',
      openingTag: 'public',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Private Method',
      description: 'Insert a PHP private method',
      replacedOnClick: 'private function methodName() {\n  \n}',
      openingTag: 'private',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Static Method',
      description: 'Insert a PHP static method',
      replacedOnClick: 'public static function methodName() {\n  \n}',
      openingTag: 'public static',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'If Statement',
      description: 'Insert a PHP if statement',
      replacedOnClick: 'if (\$condition) {\n  \n}',
      openingTag: 'if',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'If-Else',
      description: 'Insert a PHP if-else statement',
      replacedOnClick: 'if (\$condition) {\n  \n} else {\n  \n}',
      openingTag: 'if',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Switch Statement',
      description: 'Insert a PHP switch statement',
      replacedOnClick:
          'switch (\$value) {\n  case pattern:\n    \n    break;\n  default:\n    \n}',
      openingTag: 'switch',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'For Loop',
      description: 'Insert a PHP for loop',
      replacedOnClick: 'for (\$i = 0; \$i < count; \$i++) {\n  \n}',
      openingTag: 'for',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Foreach Loop',
      description: 'Insert a PHP foreach loop',
      replacedOnClick: 'foreach (\$array as \$item) {\n  \n}',
      openingTag: 'foreach',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Foreach with Key',
      description: 'Insert a PHP foreach loop with key',
      replacedOnClick: 'foreach (\$array as \$key => \$value) {\n  \n}',
      openingTag: 'foreach',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'While Loop',
      description: 'Insert a PHP while loop',
      replacedOnClick: 'while (\$condition) {\n  \n}',
      openingTag: 'while',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Do-While Loop',
      description: 'Insert a PHP do-while loop',
      replacedOnClick: 'do {\n  \n} while (\$condition);',
      openingTag: 'do',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Try-Catch',
      description: 'Insert a PHP try-catch block',
      replacedOnClick: 'try {\n  \n} catch (Exception \$e) {\n  \n}',
      openingTag: 'try',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Array',
      description: 'Insert a PHP array',
      replacedOnClick: '\$array = [];',
      openingTag: '\$',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Associative Array',
      description: 'Insert a PHP associative array',
      replacedOnClick: '\$array = ["key" => "value"];',
      openingTag: '\$',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Echo',
      description: 'Insert a PHP echo statement',
      replacedOnClick: 'echo "";',
      openingTag: 'echo',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Return',
      description: 'Insert a PHP return statement',
      replacedOnClick: 'return \$value;',
      openingTag: 'return',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Namespace',
      description: 'Insert a PHP namespace',
      replacedOnClick: 'namespace NamespaceName;',
      openingTag: 'namespace',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Use Statement',
      description: 'Insert a PHP use statement',
      replacedOnClick: 'use Namespace\\ClassName;',
      openingTag: 'use',
      closingTag: '}',
    ),
  ];
}
