import 'package:code_forge/code_forge/suggestion_model.dart';

/// Returns Ruby-specific suggestions.
List<SuggestionModel> getRubySuggestions() {
  return [
    SuggestionModel(
      label: 'Method',
      description: 'Insert a Ruby method',
      replacedOnClick: 'def method_name\n  \nend',
      openingTag: 'def',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'Method with Parameters',
      description: 'Insert a Ruby method with parameters',
      replacedOnClick: 'def method_name(param1, param2)\n  \nend',
      openingTag: 'def',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'Class',
      description: 'Insert a Ruby class',
      replacedOnClick: 'class ClassName\n  \nend',
      openingTag: 'class',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'Module',
      description: 'Insert a Ruby module',
      replacedOnClick: 'module ModuleName\n  \nend',
      openingTag: 'module',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'If Statement',
      description: 'Insert a Ruby if statement',
      replacedOnClick: 'if condition\n  \nend',
      openingTag: 'if',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'If-Else',
      description: 'Insert a Ruby if-else statement',
      replacedOnClick: 'if condition\n  \nelse\n  \nend',
      openingTag: 'if',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'Unless',
      description: 'Insert a Ruby unless statement',
      replacedOnClick: 'unless condition\n  \nend',
      openingTag: 'unless',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'Case Statement',
      description: 'Insert a Ruby case statement',
      replacedOnClick: 'case value\nwhen pattern\n  \nelse\n  \nend',
      openingTag: 'case',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'Each Loop',
      description: 'Insert a Ruby each loop',
      replacedOnClick: 'array.each do |item|\n  \nend',
      openingTag: 'each',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'Map',
      description: 'Insert a Ruby map',
      replacedOnClick: 'array.map { |item| item }',
      openingTag: 'array',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'Select',
      description: 'Insert a Ruby select',
      replacedOnClick: 'array.select { |item| condition }',
      openingTag: 'array',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'Times Loop',
      description: 'Insert a Ruby times loop',
      replacedOnClick: 'n.times do |i|\n  \nend',
      openingTag: 'times',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'While Loop',
      description: 'Insert a Ruby while loop',
      replacedOnClick: 'while condition\n  \nend',
      openingTag: 'while',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'Until Loop',
      description: 'Insert a Ruby until loop',
      replacedOnClick: 'until condition\n  \nend',
      openingTag: 'until',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'Block',
      description: 'Insert a Ruby block',
      replacedOnClick: 'do |param|\n  \nend',
      openingTag: 'do',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'Hash',
      description: 'Insert a Ruby hash',
      replacedOnClick: 'hash = { key: "value" }',
      openingTag: 'hash',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'Array',
      description: 'Insert a Ruby array',
      replacedOnClick: 'array = []',
      openingTag: 'array',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'Symbol',
      description: 'Insert a Ruby symbol',
      replacedOnClick: ':symbol',
      openingTag: ':',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'String Interpolation',
      description: 'Insert Ruby string interpolation',
      replacedOnClick: '"#{variable}"',
      openingTag: '"',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'Require',
      description: 'Insert a Ruby require statement',
      replacedOnClick: 'require "library"',
      openingTag: 'require',
      closingTag: 'end',
    ),
    SuggestionModel(
      label: 'Attr Accessor',
      description: 'Insert a Ruby attr_accessor',
      replacedOnClick: 'attr_accessor :property',
      openingTag: 'attr_accessor',
      closingTag: 'end',
    ),
  ];
}
