import 'package:code_forge/code_forge/suggestion_model.dart';

/// Returns Kotlin-specific suggestions.
List<SuggestionModel> getKotlinSuggestions() {
  return [
    SuggestionModel(
      label: 'Function',
      description: 'Insert a Kotlin function',
      replacedOnClick: 'fun functionName() {\n  \n}',
      openingTag: 'fun',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Function with Return',
      description: 'Insert a Kotlin function with return type',
      replacedOnClick: 'fun functionName(): ReturnType {\n  \n}',
      openingTag: 'fun',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Function with Parameters',
      description: 'Insert a Kotlin function with parameters',
      replacedOnClick:
          'fun functionName(param1: Type1, param2: Type2) {\n  \n}',
      openingTag: 'fun',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Class',
      description: 'Insert a Kotlin class',
      replacedOnClick: 'class ClassName {\n  \n}',
      openingTag: 'class',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Data Class',
      description: 'Insert a Kotlin data class',
      replacedOnClick: 'data class ClassName(\n  val property: Type\n)',
      openingTag: 'data class',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Sealed Class',
      description: 'Insert a Kotlin sealed class',
      replacedOnClick: 'sealed class ClassName {\n  \n}',
      openingTag: 'sealed',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Interface',
      description: 'Insert a Kotlin interface',
      replacedOnClick: 'interface InterfaceName {\n  fun method()\n}',
      openingTag: 'interface',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Object',
      description: 'Insert a Kotlin object',
      replacedOnClick: 'object ObjectName {\n  \n}',
      openingTag: 'object',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'If Expression',
      description: 'Insert a Kotlin if expression',
      replacedOnClick: 'if (condition) {\n  \n}',
      openingTag: 'if',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'If-Else',
      description: 'Insert a Kotlin if-else expression',
      replacedOnClick: 'if (condition) {\n  \n} else {\n  \n}',
      openingTag: 'if',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'When Expression',
      description: 'Insert a Kotlin when expression',
      replacedOnClick: 'when (value) {\n  pattern -> \n}',
      openingTag: 'when',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'For Loop',
      description: 'Insert a Kotlin for loop',
      replacedOnClick: 'for (item in collection) {\n  \n}',
      openingTag: 'for',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'While Loop',
      description: 'Insert a Kotlin while loop',
      replacedOnClick: 'while (condition) {\n  \n}',
      openingTag: 'while',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Do-While Loop',
      description: 'Insert a Kotlin do-while loop',
      replacedOnClick: 'do {\n  \n} while (condition)',
      openingTag: 'do',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Try-Catch',
      description: 'Insert a Kotlin try-catch block',
      replacedOnClick: 'try {\n  \n} catch (e: Exception) {\n  \n}',
      openingTag: 'try',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'List',
      description: 'Insert a Kotlin list',
      replacedOnClick: 'val list: List<Type> = listOf()',
      openingTag: 'val',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Mutable List',
      description: 'Insert a Kotlin mutable list',
      replacedOnClick: 'val list = mutableListOf<Type>()',
      openingTag: 'val',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Map',
      description: 'Insert a Kotlin map',
      replacedOnClick: 'val map: Map<KeyType, ValueType> = mapOf()',
      openingTag: 'val',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Set',
      description: 'Insert a Kotlin set',
      replacedOnClick: 'val set: Set<Type> = setOf()',
      openingTag: 'val',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Lambda',
      description: 'Insert a Kotlin lambda',
      replacedOnClick: '{ param -> value }',
      openingTag: '{',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Extension Function',
      description: 'Insert a Kotlin extension function',
      replacedOnClick: 'fun Type.extensionFunction() {\n  \n}',
      openingTag: 'fun',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Null Safety',
      description: 'Insert Kotlin null safety',
      replacedOnClick: 'val value = nullable?.property',
      openingTag: 'val',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Elvis Operator',
      description: 'Insert Kotlin elvis operator',
      replacedOnClick: 'val value = nullable ?: defaultValue',
      openingTag: 'val',
      closingTag: '}',
    ),
  ];
}
