import 'package:code_forge/code_forge/suggestion_model.dart';

/// Returns Shell/Bash-specific suggestions.
List<SuggestionModel> getShellSuggestions() {
  return [
    SuggestionModel(
      label: 'If Statement',
      description: 'Insert a bash if statement',
      replacedOnClick: 'if [ condition ]; then\n  \nfi',
      openingTag: 'if',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'If-Else',
      description: 'Insert a bash if-else statement',
      replacedOnClick: 'if [ condition ]; then\n  \nelse\n  \nfi',
      openingTag: 'if',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'If-Elif-Else',
      description: 'Insert a bash if-elif-else statement',
      replacedOnClick:
          'if [ condition ]; then\n  \nelif [ condition ]; then\n  \nelse\n  \nfi',
      openingTag: 'if',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'For Loop',
      description: 'Insert a bash for loop',
      replacedOnClick: 'for item in list; do\n  \ndone',
      openingTag: 'for',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'C-Style For Loop',
      description: 'Insert a C-style bash for loop',
      replacedOnClick: 'for ((i=0; i<10; i++)); do\n  \ndone',
      openingTag: 'for',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'While Loop',
      description: 'Insert a bash while loop',
      replacedOnClick: 'while [ condition ]; do\n  \ndone',
      openingTag: 'while',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Until Loop',
      description: 'Insert a bash until loop',
      replacedOnClick: 'until [ condition ]; do\n  \ndone',
      openingTag: 'until',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Function',
      description: 'Insert a bash function',
      replacedOnClick: 'function_name() {\n  \n}',
      openingTag: 'function',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Case Statement',
      description: 'Insert a bash case statement',
      replacedOnClick: 'case \$variable in\n  pattern)\n    \n    ;;\nesac',
      openingTag: 'case',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Select Statement',
      description: 'Insert a bash select statement',
      replacedOnClick: 'select option in list; do\n  \ndone',
      openingTag: 'select',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Test Command',
      description: 'Insert a bash test command',
      replacedOnClick: 'test condition',
      openingTag: 'test',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Echo',
      description: 'Insert a bash echo command',
      replacedOnClick: 'echo "text"',
      openingTag: 'echo',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Read Input',
      description: 'Insert a bash read command',
      replacedOnClick: 'read -p "Prompt: " variable',
      openingTag: 'read',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Variable Assignment',
      description: 'Insert a bash variable assignment',
      replacedOnClick: 'VARIABLE="value"',
      openingTag: 'VARIABLE',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Array',
      description: 'Insert a bash array',
      replacedOnClick: 'array=("item1" "item2" "item3")',
      openingTag: 'array',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Array Access',
      description: 'Insert bash array access',
      replacedOnClick: '\${array[0]}',
      openingTag: '\${',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Command Substitution',
      description: 'Insert bash command substitution',
      replacedOnClick: '\$(command)',
      openingTag: '\$(',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Arithmetic Expansion',
      description: 'Insert bash arithmetic expansion',
      replacedOnClick: '\$((expression))',
      openingTag: '\$((',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Here Document',
      description: 'Insert a bash here document',
      replacedOnClick: 'command << EOF\n  text\nEOF',
      openingTag: '<<',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Trap',
      description: 'Insert a bash trap command',
      replacedOnClick: 'trap "command" SIGNAL',
      openingTag: 'trap',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Function with Parameters',
      description: 'Insert a bash function with parameters',
      replacedOnClick:
          'function_name() {\n  local param1=\$1\n  local param2=\$2\n}',
      openingTag: 'function',
      closingTag: ';',
    ),
  ];
}
