import 'package:code_forge/code_forge/suggestion_model.dart';

/// Returns Go-specific suggestions.
List<SuggestionModel> getGoSuggestions() {
  return [
    SuggestionModel(
      label: 'Function',
      description: 'Insert a Go function',
      replacedOnClick: 'func functionName() {\n  \n}',
      openingTag: 'func',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Function with Return',
      description: 'Insert a Go function with return type',
      replacedOnClick: 'func functionName() returnType {\n  \n}',
      openingTag: 'func',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Function with Parameters',
      description: 'Insert a Go function with parameters',
      replacedOnClick: 'func functionName(param1 type1, param2 type2) {\n  \n}',
      openingTag: 'func',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Multiple Return Values',
      description: 'Insert a Go function with multiple return values',
      replacedOnClick:
          'func functionName() (type1, type2) {\n  return value1, value2\n}',
      openingTag: 'func',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Method',
      description: 'Insert a Go method',
      replacedOnClick: 'func (r Receiver) methodName() {\n  \n}',
      openingTag: 'func',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Struct',
      description: 'Insert a Go struct',
      replacedOnClick: 'type StructName struct {\n  FieldName string\n}',
      openingTag: 'type',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Interface',
      description: 'Insert a Go interface',
      replacedOnClick: 'type InterfaceName interface {\n  MethodName()\n}',
      openingTag: 'type',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'If Statement',
      description: 'Insert a Go if statement',
      replacedOnClick: 'if condition {\n  \n}',
      openingTag: 'if',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'If-Else',
      description: 'Insert a Go if-else statement',
      replacedOnClick: 'if condition {\n  \n} else {\n  \n}',
      openingTag: 'if',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'If with Initialization',
      description: 'Insert a Go if with initialization',
      replacedOnClick: 'if err := function(); err != nil {\n  \n}',
      openingTag: 'if',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Switch Statement',
      description: 'Insert a Go switch statement',
      replacedOnClick: 'switch value {\ncase pattern:\n  \ndefault:\n  \n}',
      openingTag: 'switch',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'For Loop',
      description: 'Insert a Go for loop',
      replacedOnClick: 'for i := 0; i < length; i++ {\n  \n}',
      openingTag: 'for',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'For Range',
      description: 'Insert a Go for range loop',
      replacedOnClick: 'for index, value := range collection {\n  \n}',
      openingTag: 'for',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Infinite Loop',
      description: 'Insert a Go infinite loop',
      replacedOnClick: 'for {\n  \n}',
      openingTag: 'for',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Defer',
      description: 'Insert a Go defer statement',
      replacedOnClick: 'defer function()',
      openingTag: 'defer',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Goroutine',
      description: 'Insert a Go goroutine',
      replacedOnClick: 'go function()',
      openingTag: 'go',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Channel',
      description: 'Insert a Go channel',
      replacedOnClick: 'ch := make(chan type)',
      openingTag: 'ch',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Select',
      description: 'Insert a Go select statement',
      replacedOnClick: 'select {\ncase msg := <-ch:\n  \ndefault:\n  \n}',
      openingTag: 'select',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Slice',
      description: 'Insert a Go slice',
      replacedOnClick: 'slice := []type{}',
      openingTag: 'slice',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Map',
      description: 'Insert a Go map',
      replacedOnClick: 'm := make(map[keyType]valueType)',
      openingTag: 'm',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Error Handling',
      description: 'Insert Go error handling',
      replacedOnClick: 'if err != nil {\n  return err\n}',
      openingTag: 'if',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Main Function',
      description: 'Insert a Go main function',
      replacedOnClick: 'func main() {\n  \n}',
      openingTag: 'func main',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Package',
      description: 'Insert a Go package declaration',
      replacedOnClick: 'package main',
      openingTag: 'package',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Import',
      description: 'Insert a Go import statement',
      replacedOnClick: 'import "package"',
      openingTag: 'import',
      closingTag: ';',
    ),
  ];
}
