import 'package:code_forge/code_forge/suggestion_model.dart';

/// Returns JavaScript/TypeScript-specific suggestions.
List<SuggestionModel> getJavaScriptSuggestions() {
  return [
    SuggestionModel(
      label: 'Function',
      description: 'Insert a JavaScript function',
      replacedOnClick: 'function functionName() {\n  \n}',
      openingTag: 'function',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Arrow Function',
      description: 'Insert an arrow function',
      replacedOnClick: 'const functionName = () => {\n  \n};',
      openingTag: 'const',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Async Function',
      description: 'Insert an async function',
      replacedOnClick: 'async function functionName() {\n  \n}',
      openingTag: 'async',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Async Arrow Function',
      description: 'Insert an async arrow function',
      replacedOnClick: 'const functionName = async () => {\n  \n};',
      openingTag: 'const',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Class',
      description: 'Insert a JavaScript/TypeScript class',
      replacedOnClick: 'class ClassName {\n  constructor() {\n    \n  }\n}',
      openingTag: 'class',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'If Statement',
      description: 'Insert an if statement',
      replacedOnClick: 'if (condition) {\n  \n}',
      openingTag: 'if',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'If-Else',
      description: 'Insert an if-else statement',
      replacedOnClick: 'if (condition) {\n  \n} else {\n  \n}',
      openingTag: 'if',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'For Loop',
      description: 'Insert a for loop',
      replacedOnClick: 'for (let i = 0; i < length; i++) {\n  \n}',
      openingTag: 'for',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'For-Of Loop',
      description: 'Insert a for-of loop',
      replacedOnClick: 'for (const item of array) {\n  \n}',
      openingTag: 'for',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'For-In Loop',
      description: 'Insert a for-in loop',
      replacedOnClick: 'for (const key in object) {\n  \n}',
      openingTag: 'for',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'While Loop',
      description: 'Insert a while loop',
      replacedOnClick: 'while (condition) {\n  \n}',
      openingTag: 'while',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Do-While Loop',
      description: 'Insert a do-while loop',
      replacedOnClick: 'do {\n  \n} while (condition);',
      openingTag: 'do',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Switch Statement',
      description: 'Insert a switch statement',
      replacedOnClick:
          'switch (value) {\n  case pattern:\n    \n    break;\n  default:\n    \n}',
      openingTag: 'switch',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Try-Catch',
      description: 'Insert a try-catch block',
      replacedOnClick: 'try {\n  \n} catch (error) {\n  \n}',
      openingTag: 'try',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Try-Catch-Finally',
      description: 'Insert a try-catch-finally block',
      replacedOnClick: 'try {\n  \n} catch (error) {\n  \n} finally {\n  \n}',
      openingTag: 'try',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Promise',
      description: 'Insert a Promise',
      replacedOnClick: 'new Promise((resolve, reject) => {\n  \n});',
      openingTag: 'Promise',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Async-Await',
      description: 'Insert async-await pattern',
      replacedOnClick: 'const result = await asyncFunction();',
      openingTag: 'await',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Array',
      description: 'Insert an array',
      replacedOnClick: 'const array = [];',
      openingTag: 'const',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Object',
      description: 'Insert an object',
      replacedOnClick: 'const object = {};',
      openingTag: 'const',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Map',
      description: 'Insert a Map',
      replacedOnClick: 'const map = new Map();',
      openingTag: 'const',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Set',
      description: 'Insert a Set',
      replacedOnClick: 'const set = new Set();',
      openingTag: 'const',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Template Literal',
      description: 'Insert a template literal',
      replacedOnClick: '`string \${variable}`',
      openingTag: '`',
      closingTag: '`',
    ),
    SuggestionModel(
      label: 'Export',
      description: 'Insert an export statement',
      replacedOnClick: 'export default functionName;',
      openingTag: 'export',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Import',
      description: 'Insert an import statement',
      replacedOnClick: 'import functionName from "./module";',
      openingTag: 'import',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Require',
      description: 'Insert a require statement',
      replacedOnClick: 'const module = require("./module");',
      openingTag: 'require',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'TypeScript Interface',
      description: 'Insert a TypeScript interface',
      replacedOnClick: 'interface InterfaceName {\n  property: type;\n}',
      openingTag: 'interface',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'TypeScript Type',
      description: 'Insert a TypeScript type alias',
      replacedOnClick: 'type TypeName = string;',
      openingTag: 'type',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'TypeScript Enum',
      description: 'Insert a TypeScript enum',
      replacedOnClick: 'enum EnumName {\n  Value1,\n  Value2,\n}',
      openingTag: 'enum',
      closingTag: '}',
    ),
  ];
}
