import 'package:code_forge/code_forge/suggestion_model.dart';

/// Returns Markdown-specific suggestions.
List<SuggestionModel> getMarkdownSuggestions() {
  return [
    SuggestionModel(
      label: 'Heading 1',
      description: 'Insert a level 1 heading',
      replacedOnClick: '# Heading 1',
      openingTag: '#',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Heading 2',
      description: 'Insert a level 2 heading',
      replacedOnClick: '## Heading 2',
      openingTag: '##',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Heading 3',
      description: 'Insert a level 3 heading',
      replacedOnClick: '### Heading 3',
      openingTag: '###',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Heading 4',
      description: 'Insert a level 4 heading',
      replacedOnClick: '#### Heading 4',
      openingTag: '####',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Bold Text',
      description: 'Insert bold text',
      replacedOnClick: '**bold text**',
      openingTag: '**',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Italic Text',
      description: 'Insert italic text',
      replacedOnClick: '*italic text*',
      openingTag: '*',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Bold Italic',
      description: 'Insert bold italic text',
      replacedOnClick: '***bold italic text***',
      openingTag: '***',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Inline Code',
      description: 'Insert inline code',
      replacedOnClick: '`code`',
      openingTag: '`',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Code Block',
      description: 'Insert a code block',
      replacedOnClick: '```\ncode here\n```',
      openingTag: '```',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Code Block with Language',
      description: 'Insert a code block with language',
      replacedOnClick: '```language\ncode here\n```',
      openingTag: '```',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Link',
      description: 'Insert a markdown link',
      replacedOnClick: '[link text](https://example.com)',
      openingTag: '[',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Image',
      description: 'Insert an image',
      replacedOnClick: '![alt text](image-url.jpg)',
      openingTag: '![',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Unordered List',
      description: 'Insert an unordered list item',
      replacedOnClick: '- List item',
      openingTag: '-',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Ordered List',
      description: 'Insert an ordered list item',
      replacedOnClick: '1. List item',
      openingTag: '1.',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Blockquote',
      description: 'Insert a blockquote',
      replacedOnClick: '> Quote text',
      openingTag: '>',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Horizontal Rule',
      description: 'Insert a horizontal rule',
      replacedOnClick: '---',
      openingTag: '---',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Table',
      description: 'Insert a markdown table',
      replacedOnClick:
          '| Header 1 | Header 2 |\n|----------|----------|\n| Cell 1   | Cell 2   |',
      openingTag: '|',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Strikethrough',
      description: 'Insert strikethrough text',
      replacedOnClick: '~~strikethrough text~~',
      openingTag: '~~',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Task List',
      description: 'Insert a task list item',
      replacedOnClick: '- [ ] Task item',
      openingTag: '- [',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Checked Task',
      description: 'Insert a checked task item',
      replacedOnClick: '- [x] Completed task',
      openingTag: '- [',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Reference Link',
      description: 'Insert a reference-style link',
      replacedOnClick:
          '[link text][reference]\n\n[reference]: https://example.com',
      openingTag: '[',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Footnote',
      description: 'Insert a footnote',
      replacedOnClick: 'Text[^1]\n\n[^1]: Footnote text',
      openingTag: '[^',
      closingTag: '',
    ),
  ];
}
