import 'package:code_forge/code_forge/suggestion_model.dart';

/// Returns C/C++-specific suggestions.
List<SuggestionModel> getCppSuggestions() {
  return [
    SuggestionModel(
      label: 'Function',
      description: 'Insert a C/C++ function',
      replacedOnClick: 'returnType functionName() {\n  \n}',
      openingTag: 'void',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Function with Parameters',
      description: 'Insert a C/C++ function with parameters',
      replacedOnClick:
          'returnType functionName(type param1, type param2) {\n  \n}',
      openingTag: 'void',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Class',
      description: 'Insert a C++ class',
      replacedOnClick: 'class ClassName {\npublic:\n  \nprivate:\n  \n};',
      openingTag: 'class',
      closingTag: '};',
    ),
    SuggestionModel(
      label: 'Struct',
      description: 'Insert a C/C++ struct',
      replacedOnClick: 'struct StructName {\n  type field;\n};',
      openingTag: 'struct',
      closingTag: '};',
    ),
    SuggestionModel(
      label: 'Namespace',
      description: 'Insert a C++ namespace',
      replacedOnClick: 'namespace NamespaceName {\n  \n}',
      openingTag: 'namespace',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Include',
      description: 'Insert a C/C++ include directive',
      replacedOnClick: '#include <header.h>',
      openingTag: '#include',
      closingTag: '>',
    ),
    SuggestionModel(
      label: 'Include Local',
      description: 'Insert a local include directive',
      replacedOnClick: '#include "header.h"',
      openingTag: '#include',
      closingTag: '"',
    ),
    SuggestionModel(
      label: 'Define',
      description: 'Insert a C/C++ define macro',
      replacedOnClick: '#define MACRO_NAME value',
      openingTag: '#define',
      closingTag: '',
    ),
    SuggestionModel(
      label: 'Ifdef',
      description: 'Insert a C/C++ ifdef directive',
      replacedOnClick: '#ifdef MACRO_NAME\n  \n#endif',
      openingTag: '#ifdef',
      closingTag: '#endif',
    ),
    SuggestionModel(
      label: 'Main Function',
      description: 'Insert a C/C++ main function',
      replacedOnClick: 'int main() {\n  \n  return 0;\n}',
      openingTag: 'int main',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Main with Args',
      description: 'Insert a C/C++ main function with arguments',
      replacedOnClick: 'int main(int argc, char* argv[]) {\n  \n  return 0;\n}',
      openingTag: 'int main',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'If Statement',
      description: 'Insert a C/C++ if statement',
      replacedOnClick: 'if (condition) {\n  \n}',
      openingTag: 'if',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'If-Else',
      description: 'Insert a C/C++ if-else statement',
      replacedOnClick: 'if (condition) {\n  \n} else {\n  \n}',
      openingTag: 'if',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Switch Statement',
      description: 'Insert a C/C++ switch statement',
      replacedOnClick:
          'switch (value) {\n  case pattern:\n    \n    break;\n  default:\n    \n}',
      openingTag: 'switch',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'For Loop',
      description: 'Insert a C/C++ for loop',
      replacedOnClick: 'for (int i = 0; i < n; i++) {\n  \n}',
      openingTag: 'for',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'While Loop',
      description: 'Insert a C/C++ while loop',
      replacedOnClick: 'while (condition) {\n  \n}',
      openingTag: 'while',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Do-While Loop',
      description: 'Insert a C/C++ do-while loop',
      replacedOnClick: 'do {\n  \n} while (condition);',
      openingTag: 'do',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Try-Catch',
      description: 'Insert a C++ try-catch block',
      replacedOnClick: 'try {\n  \n} catch (const std::exception& e) {\n  \n}',
      openingTag: 'try',
      closingTag: '}',
    ),
    SuggestionModel(
      label: 'Pointer',
      description: 'Insert a C/C++ pointer declaration',
      replacedOnClick: 'type* pointer;',
      openingTag: 'type',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Reference',
      description: 'Insert a C++ reference',
      replacedOnClick: 'type& reference = variable;',
      openingTag: 'type',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Template',
      description: 'Insert a C++ template',
      replacedOnClick: 'template<typename T>\nclass ClassName {\n  \n};',
      openingTag: 'template',
      closingTag: '};',
    ),
    SuggestionModel(
      label: 'Vector',
      description: 'Insert a C++ vector',
      replacedOnClick: 'std::vector<type> vec;',
      openingTag: 'std::vector',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Map',
      description: 'Insert a C++ map',
      replacedOnClick: 'std::map<keyType, valueType> map;',
      openingTag: 'std::map',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Smart Pointer',
      description: 'Insert a C++ smart pointer',
      replacedOnClick: 'std::unique_ptr<type> ptr;',
      openingTag: 'std::unique_ptr',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Lambda',
      description: 'Insert a C++ lambda function',
      replacedOnClick: 'auto lambda = [](type param) { return value; };',
      openingTag: 'auto',
      closingTag: ';',
    ),
    SuggestionModel(
      label: 'Enum',
      description: 'Insert a C/C++ enum',
      replacedOnClick: 'enum EnumName {\n  VALUE1,\n  VALUE2,\n};',
      openingTag: 'enum',
      closingTag: '};',
    ),
    SuggestionModel(
      label: 'Enum Class',
      description: 'Insert a C++ enum class',
      replacedOnClick: 'enum class EnumName {\n  VALUE1,\n  VALUE2,\n};',
      openingTag: 'enum class',
      closingTag: '};',
    ),
  ];
}
